project:
  type: book
  output-dir: .
  
book:
  title: |
    中高齢者における自転車運動の実施が  
    心身の健康に及ぼす影響
  subtitle: Effects of Cycling Exercise on Physical and Mental Health in Middle-aged and Older Adults
  author:
    name: "佐々木\\ 毅然"
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
  chapters:
    - index.qmd
    - Chapters/Chapter1.qmd  # 序章
    - Chapters/Chapter2.qmd  # 研究の背景と目的
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor: 
    name: "内田\\ 勇人\\ 教授"
  degree-name: "博士論文"
  university: 
  department: 兵庫県立大学大学院環境人間学研究科
  group: 環境人間学専攻
  faculty: Applied Math Group
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
    attribution: Dave Barry
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  logo: images/kendailogo.png
  logo-position: "between-title-and-supervisor"
  logo-height: "3.5cm"

bibliography: references.bib
csl: styles/apa.csl
cite-method: biblatex

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf:
    pdf-engine: lualatex
    documentclass: MastersDoctoralThesis
    geometry:
      - a4paper
      - total={157truemm,247truemm}
      - left=25truemm
      - right=25truemm
      - top=25truemm
      - bottom=25truemm
    classoption: 
      - "fontsize=10.5pt"
      - "oneside"
    keep-tex: true
    urlcolor: red
    toclinkcolor: black
    toc-depth: 3

